### ISSUE TITLE
update screenshot?

### ISSUE THREAD

**Issue by randomdude999** [mogria/msnake#4]
Now that the game has colors, the screenshot looks really outdated. Maybe a pic with all the edibles on it?

**Comment by randomdude999** [comment]
I've got a picture, but it doesn't have the fancy effects shown in the current one. Maybe you can add them?

![Screenshot](https://cloud.githubusercontent.com/assets/10598847/11891992/93aebe38-a56c-11e5-97a5-890a8c97c986.png)

**Comment by mogria** [comment]
I updated the screenshot, so I'm closing this one.
